Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

(c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find


i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

(g) Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]

q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]

(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),

find inner, outer and cartesian product?

In [ ]:
import numpy as np
# Question 1(a)
arr = np.array([1, 2, 3, 6, 4, 5])
arr[::-1]



array([5, 4, 6, 3, 2, 1])

In [ ]:
#1(b)
array1= np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [ ]:
#1(c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1,arr2)

True

In [ ]:
#1(d)
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

# For array x
counts_x = np.bincount(x)
most_frequent_x = np.argmax(counts_x)
indices_x = np.where(x == most_frequent_x)[0]
print("the most frequent value in x is",most_frequent_x )
print("And their indices are",indices_x )

# For array y
counts_y = np.bincount(x)
most_frequent_y = np.argmax(counts_y)
indices_y = np.where(y == most_frequent_y)[0]
print("the most frequent value in y is",most_frequent_y )
print("And their indices are",indices_y )




the most frequent value in x is 1
And their indices are [0 5 7 8 9]
the most frequent value in x is 1
And their indices are [0 1 2]


In [ ]:
#1(e)
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
sum=np.sum(gfg)
print("sum of the whole matrix",sum)
sum1=np.sum(gfg,1)
print("sum of elements row-wise",sum1)
sum2=np.sum(gfg,0)
print("sum of elements column-wise",sum2)

sum of the whole matrix 45
sum of elements row-wise [[14]
 [16]
 [15]]
sum of elements column-wise [[20  9 16]]


In [ ]:
 #1(f)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

diagonal = np.trace(n_array)
print("Sum of diagonal elements", diagonal)

eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigen values", eigenvalues)
print("Eigen vectors\n", eigenvectors)

inverse= np.linalg.inv(n_array)
print("Inverse of matrix\n", inverse)

determinant = np.linalg.det(n_array)
print("Determinant of matrix", determinant)

Sum of diagonal elements 176
Eigen values [98.16835147 28.097044   49.73460452]
Eigen vectors
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix 137180.0000000001


In [ ]:
#1(f)
p=np.array([[1,2],[2,3]])
q=np.array([[4,5],[6,7]])
ar=np.matmul(p,q)
ar2=np.cov(p,q)
print("matrix multiplication")
print(ar)
print("their covariance",ar2)

matrix multiplication
[[16 19]
 [26 31]]
their covariance [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
# 1(h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner = np.inner(x, y)
print("Inner product\n", inner)

flat1 = x.flatten()
flat2 = y.flatten()
outer= np.outer(flat1, flat2)
print("Outer product \n", outer)

cartesian= np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("\nCartesian product\n", cartesian)

Inner product:
 [[17 52]
 [13 62]]

Outer product 
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product (pairing elements)
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]).

 Find floor, ceiling
and truncated value, rounded values

In [ ]:
array=np.array([[1,-2,3],[-4,5,-6]])

abs= np.abs(array)
print("Element-wise absolute value:\n", abs)

flattened = array.flatten()
percent = np.percentile(flattened, [25, 50, 75])
print("\n25th, 50th, and 75th percentile of flattened array:", percent)

percentiles_col = np.percentile(array, [25, 50, 75], axis=0)
print("25th, 50th, and 75th percentile for each column:\n", percentiles_col)

percentiles_row = np.percentile(array, [25, 50, 75], axis=1)
print("25th, 50th, and 75th percentile for each row:\n", percentiles_row)

mean_flat = np.mean(flattened)
median_flat = np.median(flattened)
std_flat = np.std(flattened)
print("\nMean of flattened array:", mean_flat)
print("Median of flattened array:", median_flat)
print("Standard Deviation of flattened array:", std_flat)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print("Mean of each column:", mean_col)
print("Median of each column:", median_col)
print("Standard Deviation of each column:", std_col)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print("Mean of each row:", mean_row)
print("Median of each row:", median_row)
print("Standard Deviation of each row:", std_row)

Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]

25th, 50th, and 75th percentile of flattened array: [-3.5 -0.5  2.5]
25th, 50th, and 75th percentile for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
25th, 50th, and 75th percentile for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard Deviation of flattened array: 3.8622100754188224
Mean of each column: [-1.5  1.5 -1.5]
Median of each column: [-1.5  1.5 -1.5]
Standard Deviation of each column: [2.5 3.5 4.5]
Mean of each row: [ 0.66666667 -1.66666667]
Median of each row: [ 1. -4.]
Standard Deviation of each row: [2.05480467 4.78423336]


In [ ]:
# 2(b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor1 = np.floor(a)
print("Floor values", floor1)
ceil_values = np.ceil(a)
print("Ceiling values", ceil_values)
trunc = np.trunc(a)
print("Truncated values", trunc)
rounded = np.round(a)
print("Rounded values", rounded)

Floor values [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values [-1. -1. -0.  1.  2.  2.  3.]
Truncated values [-1. -1. -0.  0.  1.  1.  3.]
Rounded values [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [ ]:
# 3(a)
array_a = np.array([10, 52, 62, 16, 16, 54, 453])

sorted1 = np.sort(array_a)
print("Sorted array", sorted1)

indices = np.argsort(array_a)
print("Indices of sorted array", indices)

small = np.sort(array_a)[:4]
print("4 smallest elements", small)

large = np.sort(array_a)[::-1][:5]
print("5 largest elements", large)

Sorted array [ 10  16  16  52  54  62 453]
Indices of sorted array [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [453  62  54  52  16]


In [ ]:
# 3(b)
array= np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

only_int = array[array== array.astype(int)]
print("Integer elements only",only_int)

only_float = array[array!= array.astype(int)]
print("Float elements only:", only_float )

Integer elements only [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and

save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

(b) Load the saved file into jupyter notebook?


In [2]:
from PIL import Image
import numpy as np
import os

def img_to_array(image_path):
    image = Image.open(image_path)
    image_array = np.array(image)
    if len(image_array.shape) == 2:
        np.savetxt("grayscale_image.txt", image_array, fmt='%d')
        print("Grayscale image saved as 'grayscale_image.txt'")
    else:
        height, width, channels = image_array.shape
        flattened = image_array.reshape(-1, channels)
        np.savetxt("rgb_image.txt", flattened, fmt='%d')
        with open("rgb_shape.txt", "w") as shape_file:
            shape_file.write(f"{height} {width}")
        print("RGB image saved as 'rgb_image.txt' and shape saved in 'rgb_shape.txt'")

def load_saved_image():
    if os.path.exists("grayscale_image.txt"):
        grayscale = np.loadtxt("grayscale_image.txt", dtype=int)
        print("Loaded Grayscale Image Array:")
        print(grayscale)
        return grayscale
    elif os.path.exists("rgb_image.txt") and os.path.exists("rgb_shape.txt"):
        with open("rgb_shape.txt", "r") as shape_file:
            height, width = map(int, shape_file.read().split())
        rgb_data = np.loadtxt("rgb_image.txt", dtype=int).reshape(height, width, 3)
        print("Loaded RGB Image Array:")
        print(rgb_data)
        return rgb_data
    else:
        print("No saved image file found.")
        return None

img_to_array(r"/download.jpeg")
loaded_image = load_saved_image()

RGB image saved as 'rgb_image.txt' and shape saved in 'rgb_shape.txt'
Loaded RGB Image Array:
[[[152  79  98]
  [152  79  98]
  [154  77  97]
  ...
  [ 60  40  51]
  [ 58  41  49]
  [ 58  41  49]]

 [[152  79  98]
  [153  78  98]
  [155  78  98]
  ...
  [ 60  40  51]
  [ 59  42  50]
  [ 59  42  50]]

 [[154  79  99]
  [154  79  99]
  [156  79  99]
  ...
  [ 62  42  53]
  [ 60  43  51]
  [ 60  43  51]]

 ...

 [[ 73   7  11]
  [ 76   7  12]
  [ 88  17  23]
  ...
  [ 66  10  19]
  [ 66  10  19]
  [ 66  10  19]]

 [[ 94  23  29]
  [ 90  19  25]
  [ 85  12  19]
  ...
  [ 63   7  16]
  [ 63   7  16]
  [ 63   7  16]]

 [[100  25  30]
  [107  32  37]
  [111  34  40]
  ...
  [ 71  18  26]
  [ 73  17  26]
  [ 73  17  26]]]
